### PR TITLE
Fixing multi diagnosis detection

### PR DESCRIPTION
**Pull request by xiamaz**
Multi Diagnosis Phenotypic Series reduction did not work, because of some format issues in phenotypic series conversion.

Added a check in conversion to prevent future issues. (Especially with floats, since direct string conversion will not work well)

### CODE REVIEW

**Comment by la60312** [comment]
These selected_syndrome don't have omim_id. You also filtered out these sample. Please keep them.
```
128361
32639
34245
161571
222149
42112
128358
128364
128362
128365
```

**Comment by xiamaz** [comment]
Testing single files, this should fix the issue. But I am still running the entire pipeline to check.

**Comment by la60312** [comment]
Please check Review 3  and Todo 4 at this card https://trello.com/c/Iz0qNtnF/49-meeting-24112018

**Comment by xiamaz** [comment]
Closing because contained in #49

**Pull request closed without merging**
