### PR TITLE
Fixing phenotypic series merging in geneList

### PR DESCRIPTION
**Pull request by xiamaz**
Previously phenotypic series merging has been done before gene
translation. Because a large number of omim ids are thus ignored, the
geneList was incomplete.

Additionally detected syndromes are now generated from the syndrome
table.

Checking for multiple syndromes is now based on phenotypic series. I worked on this before receiving the list of multiple syndromes, so I am still testing the validity of results.

QC is now separate from the initial _mapping_ step. The qc outcome can be configured in the config.

**Configuration changes**

Following section needs to be added:

```
[quality]
qc_output_path = process/checked
qc_detailed = true
qc_detailed_log = quality_check.log
```

### CODE REVIEW

**Comment by la60312** [comment]
```
            "syndrome_name": "#614562 MENTAL RETARDATION, AUTOSOMAL DOMINANT 12; MRD12",
            "gene_id": "57492",
            "gene_omim_id": "ARID1B",
            "gene_symbol": "614556"
```
The naming is wrong in the gene entry generated from phenomization.

**Comment by la60312** [comment]
How did you rebase? Why you pushed the merged commit again?

**Comment by la60312** [comment]
https://help.github.com/articles/syncing-a-fork/#platform-linux

**Comment by xiamaz** [comment]
You linked an article about merging. I rebased against this branch.

I will squash my commits and open another pull request.

**Pull request closed without merging**
