### PR TITLE
VCF conversion in server mode

### PR DESCRIPTION
**Pull request by xiamaz**
Pull request mostly for discussion purposes.

Run the server by using `jannovar_server.sh` in the main directory after using snakemake on the jannovar folder.

Required config files in Trello.

### CODE REVIEW

**Comment by la60312** [comment]
The prefix variable in jannovar_server.sh is your local home directory. Could you change to ./data?

**Comment by la60312** [comment]
A stupid question, how fast the VCF convertion can be done in this patch? In one minute? I was doing the other thing, so I am not sure how long the conversion take.

**Comment by xiamaz** [comment]
I have done initial documentation here: http://pedia-workflow.readthedocs.io/en/latest/

**Comment by xiamaz** [comment]
>A stupid question, how fast the VCF convertion can be done in this patch? In one minute? I was doing the other thing, so I am not sure how long the conversion take.

The whole pipeline takes 4 minutes and 12 seconds with full cache, while regenerating all VCF files.

I have implemented multithreading for some performance critical components. This will use the number of cores available. The preprocessing can use up to approx 3gb with aggressive multithreading.

**Comment by la60312** [comment]
Do I have to use another config file? I used the one you upload in this card https://trello.com/c/MFXfTBbA/92-jannovar-server
```
raceback (most recent call last):
  File "preprocess.py", line 383, in <module>
    main()
  File "preprocess.py", line 340, in main
    config_data = config.PEDIAConfig(args)
  File "/home/la60312/pedia3/PEDIA-workflow/lib/model/config.py", line 36, in __init__
    self.input = self.parse_input(args)
  File "/home/la60312/pedia3/PEDIA-workflow/lib/model/config.py", line 93, in parse_input
    download = self["input"].getboolean(
  File "/home/la60312/miniconda3/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'input'

```

**Comment by xiamaz** [comment]
Yes, sorry about that. I posted it in trello.

**Pull request merged**
